### ISSUE TITLE
Need 'Access Control Allow Origin' Headers for Verso AJAX Call

### ISSUE THREAD

**Issue by jgreben** [lcnetdev/bfe#11]
@kirkhess I am starting to document the places where Stanford needed to make changes to this file.   This is the first one... - Josh

https://github.com/lcnetdev/bfe/blob/4169fdcde6d54e4bc332ea0e4648055c5a8382dc/builds/bfe.dev.js#L415

```
 "headers": {
                  'Access-Control-Allow-Origin': '*',
                  'Content-Type':'application/json',
                  'Access-Control-Allow-Methods': 'DELETE, HEAD, GET, OPTIONS, POST, PUT',
                  'Access-Control-Allow-Headers': 'Content-Type, Content-Range, Content-Disposition, Content-Description',
                  'Access-Control-Max-Age': '1728000'
                },
```

**Comment by jgreben** [comment]
@kirkhess if you want to create a label for these I will apply the label when I create these issues.

**Comment by kirkhess** [comment]
I'll create a label - I think this particular issue should be a single one
w/multiple comments with the files with the problems.
