### ISSUE TITLE
Need BIBFRAME 2.0 Load.json and IBC.json files in profiles

### ISSUE THREAD

**Issue by jgreben** [lcnetdev/bfe#12]
When I start the server the console errors with 404 for these files:

http://0.0.0.0:8000/static/profiles/bibframe/BIBFRAME%202.0%20Load.json
http://0.0.0.0:8000/static/profiles/bibframe/BIBFRAME%202.0%20IBC.json

Can you include these in the new Master branch?

**Comment by kirkhess** [comment]
I pushed them to dev/master but they are both going to go away in the near future once I figure out how to pick a template & I assume if we delete them no one will care - they are both a version of the monograph profile.
