### ISSUE TITLE
3.1.5 Send and receive API

### ISSUE THREAD

**Issue by kirkhess** [lcnetdev/bfe#13]
3.1.5 Prepare editor to send and receive API calls for sending and receiving profiles, templates, etc. to ML database.

Profiles are stored in a database not a file system (aka verso/marklogic)

**Comment by kirkhess** [comment]
Yes, verso should load all the profiles. In the editor one would specify which ones to load, or we can just load all of them (I think it should have a concatenate option like it does for the bf api...)

**Comment by wafschneider** [comment]
Sorry -- clarification question, my original was poorly worded and confusing -- should _bfe_ load all the profiles that are available on the verso endpoint on startup, or is that something you want to control in bfe's config.js file (as you do currently), or do you want to control it some other way?

I blame it on writing the original question too late at night :-(

**Comment by wafschneider** [comment]
Per @kirkhess: default behavior should be to load all profiles, but should be configurable in config.js.

**Comment by kirkhess** [comment]
Done.
