### ISSUE TITLE
Cannot repeat BF Provider Entities

### ISSUE THREAD

**Issue by kefo** [lcnetdev/bfe#3]
From Dan Tam Do via Jackie Shieh:

> Editor's New Instance form and have identified at least one problem with it: it currently provides no way to enter more than one Provider Entity, i.e., no way to enter a co-publisher, printer, distributor, etc.

Acknowledged.  Add a publisher/Provider and then try to add another one. Just opens the one that was just added.

**Comment by kirkhess** [comment]
This is fixed in 0.2.0.
