### ISSUE TITLE
remove builds directory contents from git repo

### ISSUE THREAD

**Issue by ndushay** [lcnetdev/bfe#40]
It would be great if code-built artifacts weren't checked into the git repo.  It avoids confusion downstream when you, for example, run grunt and correctly overwrite something and then discover that your new file shows changes because it was checked into git.

I'm new to grunt and this ecosystem, but removing all the contents of the builds directory would be a great start, and then adding `builds/*` to .gitignore

(I'm working with @jermnelson at Stanford if this seems like it's coming out of nowhere.  We've already made this change in our downstream app.  I can do a PR if you'd like.)

**Comment by kirkhess** [comment]
Good idea.  I expect periodic PRs to merge all the upstream changes so you can either do it now or wait until you finish a sprint.
