### ISSUE TITLE
BFE UI label alignment with BF vocab terms

### ISSUE THREAD

**Issue by fallgrennj** [lcnetdev/bfe#5]
As mentioned on a listserv post, we're requesting that the BFE UI labels be either more closely aligned with or replaced with the actual bf: vocab to promote understanding of and familiarity with the vocab.  While some of the examples below are clearly more confusing than others, when we stop to look these things up in the vocab and can’t readily find a match or the definition seems out of whack, we lose focus and momentum.

These comments are based on work with the BFE demo New Monograph forms and the comparisons are made to the list view of the vocab – I’ve gone through the Work and Instance sections of New Monograph for examples, but not the Holdings.

UI Label/bf vocab term
Variant title type/bf:titleType
Variant title data/bf:titleVariationDate
Other Authority Information/bf:referenceAuthority
Authority information/bf:hasAuthority
Creator role/bf:creator (actually, I’d prefer bf term to change here as the label is more descriptive)
Contributor role/bf:contributor (again, the label is more descriptive than the bf term)
Work content category/bf:contentCategory (I think this is the correct pairing per the BFE output, but the label for contentCategory in the vocab list view is Content type) 
Local identifier/bf:local (again, the label is more descriptive than the bf term)
Part title enumeration/bf:partNumber (the vocab shows the label for this term as Part Number)
Other attribute of title/bf:titleAttribute (the vocab shows the label for this term as Other title attribute)
Edition Statement/bf:edition
Media type/bf:mediaCategory
Carrier/bf:carrierCategory (but the vocab shows the label as Carrier type)
Page nos./bf:extent

‘Has derivative’ is a UI label in the Instance form, but the definition of bf:hasDerivative is “Work has a modification for which it is the source” – so is this an Instance property?

‘Is Derivative of’ is a UI label in the Instance form but the definition of bf:derivativeOf (bf:isDerativeOf is no longer valid) is “Work is a modification of a source work”, so is this an Instance property?  Should this actually be bf:derivedFrom in the Instance form?

Author, Editor, and Publication have no corresponding vocab terms, and while we obviously understand what the expected data is about, it’s not clear up front how that data is resolving in BF, e.g., as a BF Authority for author.  Most people will not have the same depth of familiarity with the BF model that you and I have, so while it may seem patently clear to us that Author data resolves to a BF Authority, it may not be as clear to others (at least at the start).

**Comment by kirkhess** [comment]
We've done a lot of work to create RDA-based profiles, which use RDA instructions as labels. If there's some interest I'll bring back the 'Kitchen-sink' view but in the pilot we didn't find that to be very useful.
