### ISSUE TITLE
question  - External access

### ISSUE THREAD

**Issue by wisaaco** [lcnetdev/bfe#51]
Hi,
I try to enable external access to the server but it does not work. My installation works locally (wget localhost: 3000, it works) but not from the outside (the server is correctly configured, there are no firewalls, etc.)

I have changed the variable:
rightBase = "http: // localhost: 3000"; with my "myIP": 3000 in config-dev.js file

What other configuration am I forgetting?
Some paths from file configurations are linked to LoC servers. Can be they a problem?

Best,
Isaac

**Comment by kirkhess** [comment]
If it works locally this sounds like a network problem to me. You can try running `node server-bfe.js` and http://{your ip}:8000/index.html should show the editor screen w/some errors if you can get to it externally.

The port in the file is 8000 - you can easily try different ports by editing the file. 
Usually port 80 is open when other ones are closed.
