### ISSUE TITLE
Include 678 Bio/Admin MARC AF 678 information?

### ISSUE THREAD

**Issue by paulfrank7** [lcnetdev/bfe#57]
MARC AF 678 is meant to be a Public Note so it has good information for this type of display. Not sure if the links below will work. 

![snap3](https://user-images.githubusercontent.com/12849256/52524231-cf70ae00-2c68-11e9-90f3-fe58110e4f2f.png)
![snap4](https://user-images.githubusercontent.com/12849256/52524232-dac3d980-2c68-11e9-8431-0618fc13ddb2.jpg)

**Comment by thisismattmiller** [comment]
To add this to the list we would use the MADS property http://www.loc.gov/mads/rdf/v1#note in ID

**Comment by paulfrank7** [comment]
Ok, sounds good, I do not see another MADS property that would work for this. Paul
