### ISSUE TITLE
Add MARC AF 663 complex pseudonym information? 

### ISSUE THREAD

**Issue by paulfrank7** [lcnetdev/bfe#58]
Addition of MARC AF 663 data may be helpful.
![snap 7](https://user-images.githubusercontent.com/12849256/52524484-7c4c2a80-2c6b-11e9-8f74-fff262836e48.jpg)
![snap8](https://user-images.githubusercontent.com/12849256/52524490-7eae8480-2c6b-11e9-817d-955dddc656f8.jpg)

**Comment by thisismattmiller** [comment]
It doesn't look like this is represented in the MADS record: http://id.loc.gov/authorities/names/no2017157927.html at the moment

**Comment by paulfrank7** [comment]
It’s ok I guess, we can just rely on the Related Terms:

[cid:image001.png@01D4CA07.28452930]

Paul
