### ISSUE TITLE
Enhancement: add support for optional values (drop-down lists)

### ISSUE THREAD

**Issue by Timathom** [lcnetdev/bfe#7]
As an alternative/complement to lookups, I'd like to be able to define a list of values to select from a drop-down menu. The BFE's implementation of the Profiles spec lets users define default values for resource properties ("defaultURI" and "defaultLiteral"). It would also be great to have something like "optionalURIs" and "optionalLiterals" that a user could easily choose from, without having to do multiple lookups.

**Comment by kirkhess** [comment]
We did this with one of the RDA fields - see bfelookups.js
                $.ajax({
                    url: u,
                    dataType: "json",
                    success: function (data) {
                        parsedlist = lcshared.processJSONLDSuggestions(data,query,exports.scheme);
                        return process(parsedlist);
                    }
